USE [master]
GO

/****** Object:  Database [Medius_Database]    Script Date: 8/9/2022 8:51:10 AM ******/
CREATE DATABASE [Medius_Database]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Medius_Database', FILENAME = N'/var/opt/mssql/data/Medius_Database.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Medius_Database_log', FILENAME = N'/var/opt/mssql/data/Medius_Database_log.ldf' , SIZE = 598016KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Medius_Database].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Medius_Database] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Medius_Database] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Medius_Database] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Medius_Database] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Medius_Database] SET ARITHABORT OFF 
GO

ALTER DATABASE [Medius_Database] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Medius_Database] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Medius_Database] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Medius_Database] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Medius_Database] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Medius_Database] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Medius_Database] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Medius_Database] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Medius_Database] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Medius_Database] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Medius_Database] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Medius_Database] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Medius_Database] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Medius_Database] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Medius_Database] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Medius_Database] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Medius_Database] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Medius_Database] SET RECOVERY FULL 
GO

ALTER DATABASE [Medius_Database] SET  MULTI_USER 
GO

ALTER DATABASE [Medius_Database] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Medius_Database] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Medius_Database] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Medius_Database] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Medius_Database] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Medius_Database] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Medius_Database] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Medius_Database] SET  READ_WRITE 
GO


